version: "3"

services:
    database:
        image: "postgres:11-alpine"
        volumes:
            - ./sql/schema.sql:/schema.sql
            - ./scripts/postgres-init.sh:/docker-entrypoint-initdatabase.d/postgres-init.sh
    redis:
        image: "redis:alpine"
    worker:
        build:
            context: "."
            dockerfile: "docker/Dockerfile.worker"
        command: bash -c 'while !</dev/tcp/database/5432; do echo "waiting for database"; sleep 1; done; /worker'
        depends_on:
            - database
        environment:
            REDIS_URL: 'redis://redis:6379'
    website:
        build:
            context: "."
            dockerfile: "docker/Dockerfile.website"
        command: bash -c 'while !</dev/tcp/database/5432; do echo "waiting for database"; sleep 1; done; /website-launcher'
        depends_on:
            - database
            - redis
        environment:
            REDIS_URL: 'redis://redis:6379'
        ports:
            - "3000:3000"
    discord:
        build:
            context: "."
            dockerfile: "docker/Dockerfile.discord"
        command: bash -c 'while !</dev/tcp/database/5432; do echo "waiting for database"; sleep 1; done; /discord-launcher'
        depends_on:
            - database
        environment:
            REDIS_URL: 'redis://redis:6379'
    twitch:
        build:
            context: "."
            dockerfile: "docker/Dockerfile.twitch"
        command: bash -c 'while !</dev/tcp/database/5432; do echo "waiting for database"; sleep 1; done; /twitch-launcher'
        depends_on:
            - database
        environment:
            REDIS_URL: 'redis://redis:6379'
    dogecoind:
        image: 'greenbigfrog/dogecoin'
        volumes:
            - ./dogecoin.conf:/dogecoin/.dogecoin/dogecoin.conf
            - dogecoin:/dogecoin/
        command: 'dogecoind -printtoconsole -testnet'

volumes:
    dogecoin:
