version: "3"

services:
    database:
        networks:
            - db_bot
            - redis_worker
        image: "postgres:11-alpine"
        volumes:
            - ./sql/schema.sql:/schema.sql
            - ./scripts/postgres-init.sh:/docker-entrypoint-initdb.d/postgres-init.sh
    redis:
        networks:
            - redis_bot
            - redis_worker
        image: "redis:alpine"
    worker:
        networks:
            - db_bot
            - redis_worker
        depends_on:
            - redis
            - database
        build: 
            context: "."
            dockerfile: "docker/Dockerfile.worker"
        volumes:
            - ./tipbot/config.json:/config.json
        environment:
            REDIS_URL: 'redis://redis:6379'
    discord_bot:
        networks:
            - db_bot
            - redis_bot
        build: 
            context: "."
            dockerfile: "docker/Dockerfile.discord"
        depends_on:
            - redis
            - database
        volumes:
            - ./tipbot/config.json:/config.json
    twitch_bot:
        networks:
            - db_bot
            - redis_bot
        build:  
            context: "."
            dockerfile: "docker/Dockerfile.twitch"
        depends_on:
            - redis
            - database
        volumes:
            - ./tipbot/config.json:/config.json

networks:
    db_bot:
        driver: overlay
    redis_bot:
        driver: overlay
    redis_worker:
        driver: overlay