version: "3"

services:
    database:
        image: "postgres:11-alpine"
        volumes:
            - ./sql/schema.sql:/schema.sql
            - ./scripts/postgres-init.sh:/docker-entrypoint-initdb.d/postgres-init.sh
    redis:
        image: "redis:alpine"
    worker:
        build: 
            context: "."
            dockerfile: "docker/Dockerfile.worker"
        volumes:
            - ./tipbot/config.json:/config.json
        command: bash -c 'while !</dev/tcp/db/5432; do echo "waiting for database"; sleep 1; done; /worker'
        depends_on:
            - database
        environment:
            REDIS_URL: 'redis://redis:6379'
    discord:
        build: 
            context: "."
            dockerfile: "docker/Dockerfile.discord"
        volumes:
            - ./tipbot/config.json:/config.json
        command: bash -c 'while !</dev/tcp/db/5432; do echo "waiting for database"; sleep 1; done; /discord_launcher'
        depends_on:
            - database
        environment:
            REDIS_URL: 'redis://redis:6379'
    twitch:
        build:
            context: "."
            dockerfile: "docker/Dockerfile.twitch"
        volumes:
            - ./tipbot/config.json:/config.json
        command: bash -c 'while !</dev/tcp/db/5432; do echo "waiting for database"; sleep 1; done; /twitch_launcher'
        depends_on:
            - database
        environment:
            REDIS_URL: 'redis://redis:6379'